In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [2]:
df = sns.load_dataset('diamonds')

In [3]:
df.head()

   carat      cut color clarity  depth  table  price     x     y     z
0   0.23    Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1   0.21  Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2   0.23     Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3   0.29  Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4   0.31     Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 53940 entries, 0 to 53939
Data columns (total 10 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   carat    53940 non-null  float64
 1   cut      53940 non-null  category
 2   color    53940 non-null  category
 3   clarity  53940 non-null  category
 4   depth    53940 non-null  float64
 5   table    53940 non-null  float64
 6   price    53940 non-null  int64
 7   x        53940 non-null  float64
 8   y        53940 non-null  float64
 9   z        53940 non-null  float64
dtypes: category(3), float64(6), int64(1)
memory usage: 3.0 MB

In [5]:
df.isna().sum()

carat      0
cut        0
color      0
clarity    0
depth      0
table      0
price      0
x          0
y          0
z          0
dtype: int64

In [6]:
df.shape

(53940, 10)

In [7]:
df.describe()

,carat,depth,table,price,x,y,z
count,53940.000000,53940.000000,53940.000000,53940.000000,53940.000000,53940.000000,53940.000000
mean,0.797940,61.749405,57.457184,3932.799722,5.731157,5.734526,3.538734
std,0.474011,1.432621,2.234491,3989.439738,1.121761,1.142135,0.705699
min,0.200000,43.000000,43.000000,326.000000,0.000000,0.000000,0.000000
25%,0.400000,61.000000,56.000000,950.000000,4.710000,4.720000,2.910000
50%,0.700000,61.800000,57.000000,2401.000000,5.700000,5.710000,3.530000
75%,1.040000,62.500000,59.000000,5324.250000,6.540000,6.540000,4.040000
max,5.010000,79.000000,95.000000,18823.000000,10.740000,58.900000,31.800000

In [10]:
X = df.drop('price', axis=1)
y = df['price']

In [11]:
from sklearn.model_selection import train_test_split

In [12]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [13]:
X_train.head()

       carat        cut color clarity  depth  table     x     y     z
26546   2.01       Good     F     SI2   58.1   64.0  8.23  8.19  4.77
9159    1.01  Very Good     E     SI2   60.0   60.0  6.57  6.49  3.92
14131   1.10    Premium     H     VS2   62.5   58.0  6.59  6.54  4.10
15757   1.50       Good     E     SI2   61.5   65.0  7.21  7.17  4.42
24632   1.52  Very Good     G     VS1   62.1   57.0  7.27  7.32  4.53

In [14]:
X_train['cut'].value_counts()

cut
Ideal        17259
Premium      11016
Very Good     9700
Good          3902
Fair          1275
Name: count, dtype: int64

In [16]:
X_train['color'].value_counts()

color
G    9015
E    7863
F    7644
H    6707
D    5413
I    4274
J    2236
Name: count, dtype: int64

In [17]:
X_train['clarity'].value_counts()

clarity
SI1     10520
VS2      9793
SI2      7306
VS1      6530
VVS2     4044
VVS1     2944
IF       1430
I1        585
Name: count, dtype: int64

In [18]:
from sklearn.preprocessing import OrdinalEncoder

In [19]:
oe = OrdinalEncoder(
    categories = [
        ['Fair', 'Good', 'Very Good', 'Premium', 'Ideal'],
        ['J', 'I', 'H', 'G', 'F', 'E', 'D'],
        ['I1', 'SI2', 'SI1', 'VS2', 'VS1', 'VVS2', 'VVS1', 'IF']
    ]
)

In [20]:
X_train[['cut', 'color', 'clarity']] = oe.fit_transform(X_train[['cut', 'color', 'clarity']])

In [22]:
X_train.head()

       carat  cut  color  clarity  depth  table     x     y     z
26546   2.01  1.0    4.0      1.0   58.1   64.0  8.23  8.19  4.77
9159    1.01  2.0    5.0      1.0   60.0   60.0  6.57  6.49  3.92
14131   1.10  3.0    2.0      3.0   62.5   58.0  6.59  6.54  4.10
15757   1.50  1.0    5.0      1.0   61.5   65.0  7.21  7.17  4.42
24632   1.52  2.0    3.0      4.0   62.1   57.0  7.27  7.32  4.53

In [23]:
X_test[['cut', 'color', 'clarity']] = oe.transform(X_test[['cut', 'color', 'clarity']])

In [24]:
y_train.head()

26546    16231
9159      4540
14131     5729
15757     6300
24632    12968
Name: price, dtype: int64

In [26]:
from sklearn.tree import DecisionTreeRegressor

In [29]:
model = DecisionTreeRegressor()

In [30]:
model.fit(X_train, y_train)

DecisionTreeRegressor()

In [31]:
y_pred = model.predict(X_test)

In [35]:
from sklearn.metrics import r2_score

In [36]:
r2_score(y_test, y_pred)

0.966279444661371