In [1]:
import pandas as pd

df = pd.DataFrame({
    'age': [22, 35, 28, 41, 30, 26, 38, 45],
    'education': [
        'High School', 'Bachelor', 'Master', 'PhD',
        'Bachelor', 'High School', 'Master', 'PhD'
    ],
    'employment_type': [
        'Private', 'Government', 'Private', 'Self-employed',
        'Government', 'Private', 'Self-employed', 'Private'
    ],
    'satisfaction': [
        'Poor', 'Good', 'Excellent', 'Average',
        'Good', 'Poor', 'Excellent', 'Average'
    ],
    'remote_worker': [
        'Yes', 'No', 'Yes', 'Yes',
        'No', 'No', 'Yes', 'No'
    ],
    'city': [
        'Lahore', 'Islamabad', 'Karachi', 'Lahore',
        'Peshawar', 'Karachi', 'Islamabad', 'Lahore'
    ],
    'salary': [
        45000, 85000, 120000, 150000,
        90000, 50000, 130000, 160000
    ]
})

In [2]:
df

,age,education,employment_type,satisfaction,remote_worker,city,salary
0,22,High School,Private,Poor,Yes,Lahore,45000
1,35,Bachelor,Government,Good,No,Islamabad,85000
2,28,Master,Private,Excellent,Yes,Karachi,120000
3,41,PhD,Self-employed,Average,Yes,Lahore,150000
4,30,Bachelor,Government,Good,No,Peshawar,90000
5,26,High School,Private,Poor,No,Karachi,50000
6,38,Master,Self-employed,Excellent,Yes,Islamabad,130000
7,45,PhD,Private,Average,No,Lahore,160000

In [3]:
df['remote_worker'].value_counts()

remote_worker
Yes    4
No     4
Name: count, dtype: int64

In [4]:
# Binary categorical feature

In [5]:
df['remote_worker'] = df['remote_worker'].map({
    'Yes': 1,
    'No': 0
})

In [6]:
df

,age,education,employment_type,satisfaction,remote_worker,city,salary
0,22,High School,Private,Poor,1,Lahore,45000
1,35,Bachelor,Government,Good,0,Islamabad,85000
2,28,Master,Private,Excellent,1,Karachi,120000
3,41,PhD,Self-employed,Average,1,Lahore,150000
4,30,Bachelor,Government,Good,0,Peshawar,90000
5,26,High School,Private,Poor,0,Karachi,50000
6,38,Master,Self-employed,Excellent,1,Islamabad,130000
7,45,PhD,Private,Average,0,Lahore,160000

In [7]:
df['satisfaction'].value_counts()

satisfaction
Poor         2
Good         2
Excellent    2
Average      2
Name: count, dtype: int64

In [8]:
df['education'].value_counts()

education
High School    2
Bachelor       2
Master         2
PhD            2
Name: count, dtype: int64

In [9]:
# meaningful 0rder

In [10]:
from sklearn.preprocessing import OrdinalEncoder

In [11]:
oe = OrdinalEncoder(categories=[
    ['High School', 'Bachelor', 'Master', 'PhD'], # school < bachelor < master < PhD
    ['Poor', 'Average', 'Good', 'Excellent'] # poor < average < good < excellent
])

In [12]:
df[['education', 'satisfaction']] = oe.fit_transform(df[['education', 'satisfaction']])

In [13]:
df

,age,education,employment_type,satisfaction,remote_worker,city,salary
0,22,0.0,Private,0.0,1,Lahore,45000
1,35,1.0,Government,2.0,0,Islamabad,85000
2,28,2.0,Private,3.0,1,Karachi,120000
3,41,3.0,Self-employed,1.0,1,Lahore,150000
4,30,1.0,Government,2.0,0,Peshawar,90000
5,26,0.0,Private,0.0,0,Karachi,50000
6,38,2.0,Self-employed,3.0,1,Islamabad,130000
7,45,3.0,Private,1.0,0,Lahore,160000

In [14]:
df['employment_type'].value_counts()

employment_type
Private          4
Government       2
Self-employed    2
Name: count, dtype: int64

In [15]:
df['city'].value_counts()

city
Lahore       3
Islamabad    2
Karachi      2
Peshawar     1
Name: count, dtype: int64

In [18]:
# nominal features -> one-hot encoding

In [16]:
df = pd.get_dummies(df, columns=['employment_type', 'city'], drop_first=True, dtype=int)

In [17]:
df

,age,education,satisfaction,remote_worker,salary,employment_type_Private,employment_type_Self-employed,city_Karachi,city_Lahore,city_Peshawar
0,22,0.0,0.0,1,45000,1,0,0,1,0
1,35,1.0,2.0,0,85000,0,0,0,0,0
2,28,2.0,3.0,1,120000,1,0,1,0,0
3,41,3.0,1.0,1,150000,0,1,0,1,0
4,30,1.0,2.0,0,90000,0,0,0,0,1
5,26,0.0,0.0,0,50000,1,0,1,0,0
6,38,2.0,3.0,1,130000,0,1,0,0,0
7,45,3.0,1.0,0,160000,1,0,0,1,0