In [1]:
import pandas as pd

df = pd.DataFrame({
    'City': ['Lahore', 'Karachi', 'Islamabad', 'Lahore', 'Peshawar', 'Karachi'],
    'Gender': ['Male', 'Female', 'Male', 'Female', 'Male', 'Male'],
    'Age': [22, 25, 21, 24, 23, 26],
    'Salary': [50000, 65000, 45000, 55000, 48000, 70000]
})

print(df)

        City  Gender  Age  Salary
0     Lahore    Male   22   50000
1    Karachi  Female   25   65000
2  Islamabad    Male   21   45000
3     Lahore  Female   24   55000
4   Peshawar    Male   23   48000
5    Karachi    Male   26   70000

In [2]:
from sklearn.preprocessing import OneHotEncoder

encoder = OneHotEncoder(sparse_output=False)

encoded = encoder.fit_transform(df[['City', 'Gender']])

print(encoded)
print(encoder.get_feature_names_out())

[[0. 0. 1. 0. 0. 1.]
 [0. 1. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 1. 0.]
 [0. 0. 0. 1. 0. 1.]
 [0. 1. 0. 0. 0. 1.]]
['City_Islamabad' 'City_Karachi' 'City_Lahore' 'City_Peshawar'
 'Gender_Female' 'Gender_Male']

In [3]:
from sklearn.preprocessing import OneHotEncoder
import pandas as pd

encoder = OneHotEncoder(sparse_output=False)

encoded = encoder.fit_transform(df[['City', 'Gender']])

encoded_df = pd.DataFrame(
    encoded,
    columns=encoder.get_feature_names_out(['City', 'Gender']),
    index=df.index
)

print(encoded_df)

   City_Islamabad  City_Karachi  City_Lahore  City_Peshawar  Gender_Female  \
0             0.0           0.0          1.0            0.0            0.0
1             0.0           1.0          0.0            0.0            1.0
2             1.0           0.0          0.0            0.0            0.0
3             0.0           0.0          1.0            0.0            1.0
4             0.0           0.0          0.0            1.0            0.0
5             0.0           1.0          0.0            0.0            0.0

   Gender_Male
0          1.0
1          0.0
2          1.0
3          0.0
4          1.0
5          1.0

In [4]:
import pandas as pd

df = pd.DataFrame({
    'City': ['Lahore', 'Islamabad', 'Karachi', 'Lahore'],
    'Age': [20, 21, 19, 22]
})

print(df)

        City  Age
0     Lahore   20
1  Islamabad   21
2    Karachi   19
3     Lahore   22

In [13]:
df['City'].value_counts()

City
Lahore       2
Islamabad    1
Karachi      1
Name: count, dtype: int64

In [6]:
from sklearn.preprocessing import OneHotEncoder

In [16]:
encoder = OneHotEncoder(sparse_output=False).set_output(transform='pandas')

In [17]:
encoded = encoder.fit_transform(df[['City']])

In [18]:
encoded

   City_Islamabad  City_Karachi  City_Lahore
0             0.0           0.0          1.0
1             1.0           0.0          0.0
2             0.0           1.0          0.0
3             0.0           0.0          1.0

In [11]:
encoded.toarray()

array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [14]:
encoder.categories_

[array(['Islamabad', 'Karachi', 'Lahore'], dtype=object)]

In [20]:
import pandas as pd

df = pd.DataFrame({
    'City': ['Lahore', 'Karachi', 'Islamabad', 'Lahore', 'Peshawar', 'Karachi'],
    'Gender': ['Male', 'Female', 'Male', 'Female', 'Male', 'Male'],
    'Age': [22, 25, 21, 24, 23, 26],
    'Salary': [50000, 65000, 45000, 55000, 48000, 70000]
})

In [21]:
df

        City  Gender  Age  Salary
0     Lahore    Male   22   50000
1    Karachi  Female   25   65000
2  Islamabad    Male   21   45000
3     Lahore  Female   24   55000
4   Peshawar    Male   23   48000
5    Karachi    Male   26   70000

In [22]:
df['City'].value_counts()

City
Lahore       2
Karachi      2
Islamabad    1
Peshawar     1
Name: count, dtype: int64

In [25]:
df['Gender'].value_counts()

Gender
Male      4
Female    2
Name: count, dtype: int64

In [23]:
from sklearn.preprocessing import OneHotEncoder

In [24]:
encoder = OneHotEncoder(sparse_output=False, drop='first').set_output(transform='pandas')

In [32]:
encoded = encoder.fit_transform(df[['City', 'Gender']])

In [43]:
encoded_df = df[['Age', 'Salary']].copy()

In [44]:
encoded_df[encoded.columns] = encoded

In [45]:
encoded_df

   Age  Salary  City_Karachi  City_Lahore  City_Peshawar  Gender_Male
0   22   50000           0.0          1.0            0.0          1.0
1   25   65000           1.0          0.0            0.0          0.0
2   21   45000           0.0          0.0            0.0          1.0
3   24   55000           0.0          1.0            0.0          0.0
4   23   48000           0.0          0.0            1.0          1.0
5   26   70000           1.0          0.0            0.0          1.0

In [47]:
import pandas as pd
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [48]:
df = pd.DataFrame({
    'City': ['Lahore', 'Karachi', 'Islamabad', 'Lahore', 'Peshawar', 'Karachi'],
    'Gender': ['Male', 'Female', 'Male', 'Female', 'Male', 'Male'],
    'Age': [22, 25, 21, 24, 23, 26],
    'Salary': [50000, 65000, 45000, 55000, 48000, 70000]
})

In [50]:
df

        City  Gender  Age  Salary
0     Lahore    Male   22   50000
1    Karachi  Female   25   65000
2  Islamabad    Male   21   45000
3     Lahore  Female   24   55000
4   Peshawar    Male   23   48000
5    Karachi    Male   26   70000

In [49]:
cat_cols = ['City', 'Gender']

In [51]:
preprocessor = ColumnTransformer(
    transformers=[
        (
            'cat',
            OneHotEncoder(
                drop='first',
                sparse_output=False
            ),
            cat_cols
        )
    ],
    remainder='passthrough'
).set_output(transform='pandas')

In [52]:
encoded_df = preprocessor.fit_transform(df)

In [53]:
encoded_df

,cat__City_Karachi,cat__City_Lahore,cat__City_Peshawar,cat__Gender_Male,remainder__Age,remainder__Salary
0,0.0,1.0,0.0,1.0,22,50000
1,1.0,0.0,0.0,0.0,25,65000
2,0.0,0.0,0.0,1.0,21,45000
3,0.0,1.0,0.0,0.0,24,55000
4,0.0,0.0,1.0,1.0,23,48000
5,1.0,0.0,0.0,1.0,26,70000

In [54]:
df = pd.DataFrame({
    'City': ['Lahore', 'Karachi', 'Islamabad', 'Lahore', 'Karachi'],
    'Gender': ['Male', 'Female', 'Male', 'Female', 'Male'],
    'Age': [20, 21, 19, 22, 20]
})

In [55]:
df

        City  Gender  Age
0     Lahore    Male   20
1    Karachi  Female   21
2  Islamabad    Male   19
3     Lahore  Female   22
4    Karachi    Male   20

In [56]:
from sklearn.preprocessing import OneHotEncoder

encoder = OneHotEncoder(sparse_output=False)

In [57]:
encoder.fit(df[['City']])

OneHotEncoder(sparse_output=False)

In [58]:
encoder.categories_

[array(['Islamabad', 'Karachi', 'Lahore'], dtype=object)]

In [60]:
encoded = encoder.transform(df[['City']])
encoded

array([[0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.]])

In [61]:
encoder.get_feature_names_out()

array(['City_Islamabad', 'City_Karachi', 'City_Lahore'], dtype=object)

In [62]:
df[encoder.get_feature_names_out()] = encoded

In [63]:
df

        City  Gender  Age  City_Islamabad  City_Karachi  City_Lahore
0     Lahore    Male   20             0.0           0.0          1.0
1    Karachi  Female   21             0.0           1.0          0.0
2  Islamabad    Male   19             1.0           0.0          0.0
3     Lahore  Female   22             0.0           0.0          1.0
4    Karachi    Male   20             0.0           1.0          0.0

In [64]:
df = df.drop(columns=['City'])

In [65]:
df

   Gender  Age  City_Islamabad  City_Karachi  City_Lahore
0    Male   20             0.0           0.0          1.0
1  Female   21             0.0           1.0          0.0
2    Male   19             1.0           0.0          0.0
3  Female   22             0.0           0.0          1.0
4    Male   20             0.0           1.0          0.0

In [66]:
df = pd.DataFrame({
    'City': ['Lahore', 'Karachi', 'Islamabad', 'Lahore', 'Karachi'],
    'Gender': ['Male', 'Female', 'Male', 'Female', 'Male'],
    'Age': [20, 21, 19, 22, 20]
})

In [67]:
df

        City  Gender  Age
0     Lahore    Male   20
1    Karachi  Female   21
2  Islamabad    Male   19
3     Lahore  Female   22
4    Karachi    Male   20

In [68]:
encoder = OneHotEncoder(sparse_output=False)

encoder.fit(df[['City', 'Gender']])

OneHotEncoder(sparse_output=False)

In [69]:
encoder.categories_

[array(['Islamabad', 'Karachi', 'Lahore'], dtype=object),
 array(['Female', 'Male'], dtype=object)]

In [70]:
encoded = encoder.transform(df[['City', 'Gender']])

In [71]:
encoder.get_feature_names_out()

array(['City_Islamabad', 'City_Karachi', 'City_Lahore', 'Gender_Female',
       'Gender_Male'], dtype=object)

In [72]:
df[encoder.get_feature_names_out()] = encoded