In [1]:
import pandas as pd

df = pd.DataFrame({
    'City': ['Lahore', 'Karachi', 'Islamabad', 'Lahore', 'Peshawar', 'Karachi'],
    'Gender': ['Male', 'Female', 'Male', 'Female', 'Male', 'Male'],
    'Age': [22, 25, 21, 24, 23, 26],
    'Salary': [50000, 65000, 45000, 55000, 48000, 70000]
})

print(df)

        City  Gender  Age  Salary
0     Lahore    Male   22   50000
1    Karachi  Female   25   65000
2  Islamabad    Male   21   45000
3     Lahore  Female   24   55000
4   Peshawar    Male   23   48000
5    Karachi    Male   26   70000

In [2]:
from sklearn.preprocessing import OneHotEncoder

encoder = OneHotEncoder(sparse_output=False)

encoded = encoder.fit_transform(df[['City', 'Gender']])

print(encoded)
print(encoder.get_feature_names_out())

[[0. 0. 1. 0. 0. 1.]
 [0. 1. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 1. 0.]
 [0. 0. 0. 1. 0. 1.]
 [0. 1. 0. 0. 0. 1.]]
['City_Islamabad' 'City_Karachi' 'City_Lahore' 'City_Peshawar'
 'Gender_Female' 'Gender_Male']

In [3]:
from sklearn.preprocessing import OneHotEncoder
import pandas as pd

encoder = OneHotEncoder(sparse_output=False)

encoded = encoder.fit_transform(df[['City', 'Gender']])

encoded_df = pd.DataFrame(
    encoded,
    columns=encoder.get_feature_names_out(['City', 'Gender']),
    index=df.index
)

print(encoded_df)

   City_Islamabad  City_Karachi  City_Lahore  City_Peshawar  Gender_Female  \
0             0.0           0.0          1.0            0.0            0.0
1             0.0           1.0          0.0            0.0            1.0
2             1.0           0.0          0.0            0.0            0.0
3             0.0           0.0          1.0            0.0            1.0
4             0.0           0.0          0.0            1.0            0.0
5             0.0           1.0          0.0            0.0            0.0

   Gender_Male
0          1.0
1          0.0
2          1.0
3          0.0
4          1.0
5          1.0

In [4]:
import pandas as pd

df = pd.DataFrame({
    'City': ['Lahore', 'Islamabad', 'Karachi', 'Lahore'],
    'Age': [20, 21, 19, 22]
})

print(df)

        City  Age
0     Lahore   20
1  Islamabad   21
2    Karachi   19
3     Lahore   22

In [13]:
df['City'].value_counts()

City
Lahore       2
Islamabad    1
Karachi      1
Name: count, dtype: int64

In [6]:
from sklearn.preprocessing import OneHotEncoder

In [16]:
encoder = OneHotEncoder(sparse_output=False).set_output(transform='pandas')

In [17]:
encoded = encoder.fit_transform(df[['City']])

In [18]:
encoded

   City_Islamabad  City_Karachi  City_Lahore
0             0.0           0.0          1.0
1             1.0           0.0          0.0
2             0.0           1.0          0.0
3             0.0           0.0          1.0

In [11]:
encoded.toarray()

array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [14]:
encoder.categories_

[array(['Islamabad', 'Karachi', 'Lahore'], dtype=object)]

In [20]:
import pandas as pd

df = pd.DataFrame({
    'City': ['Lahore', 'Karachi', 'Islamabad', 'Lahore', 'Peshawar', 'Karachi'],
    'Gender': ['Male', 'Female', 'Male', 'Female', 'Male', 'Male'],
    'Age': [22, 25, 21, 24, 23, 26],
    'Salary': [50000, 65000, 45000, 55000, 48000, 70000]
})

In [21]:
df

        City  Gender  Age  Salary
0     Lahore    Male   22   50000
1    Karachi  Female   25   65000
2  Islamabad    Male   21   45000
3     Lahore  Female   24   55000
4   Peshawar    Male   23   48000
5    Karachi    Male   26   70000

In [22]:
df['City'].value_counts()

City
Lahore       2
Karachi      2
Islamabad    1
Peshawar     1
Name: count, dtype: int64

In [25]:
df['Gender'].value_counts()

Gender
Male      4
Female    2
Name: count, dtype: int64

In [23]:
from sklearn.preprocessing import OneHotEncoder

In [24]:
encoder = OneHotEncoder(sparse_output=False, drop='first').set_output(transform='pandas')

In [32]:
encoded = encoder.fit_transform(df[['City', 'Gender']])

In [43]:
encoded_df = df[['Age', 'Salary']].copy()

In [44]:
encoded_df[encoded.columns] = encoded

In [45]:
encoded_df

   Age  Salary  City_Karachi  City_Lahore  City_Peshawar  Gender_Male
0   22   50000           0.0          1.0            0.0          1.0
1   25   65000           1.0          0.0            0.0          0.0
2   21   45000           0.0          0.0            0.0          1.0
3   24   55000           0.0          1.0            0.0          0.0
4   23   48000           0.0          0.0            1.0          1.0
5   26   70000           1.0          0.0            0.0          1.0