In [1]:
import pandas as pd

In [11]:
df = pd.DataFrame({
    "Name": ["Ali", "Sana", "Saba", "Fahad", "Aryan"],
    "Gender": ["Male", "Female", "Female", "Male", "Male"],
    "Score": [98, 78, 95, 64, 87]
})

In [12]:
df

    Name  Gender  Score
0    Ali    Male     98
1   Sana  Female     78
2   Saba  Female     95
3  Fahad    Male     64
4  Aryan    Male     87

In [13]:
df['G'] = df['Gender'].map({'Male': 'M', 'Female': 'F'})

In [14]:
df

    Name  Gender  Score  G
0    Ali    Male     98  M
1   Sana  Female     78  F
2   Saba  Female     95  F
3  Fahad    Male     64  M
4  Aryan    Male     87  M

In [15]:
df['Ge'] = df['G'].replace({'M': 'Ma'})

In [16]:
df

    Name  Gender  Score  G  Ge
0    Ali    Male     98  M  Ma
1   Sana  Female     78  F   F
2   Saba  Female     95  F   F
3  Fahad    Male     64  M  Ma
4  Aryan    Male     87  M  Ma

In [17]:
df['Ge'] = df['Ge'].replace({'F': 'Fe'})

In [18]:
df

    Name  Gender  Score  G  Ge
0    Ali    Male     98  M  Ma
1   Sana  Female     78  F  Fe
2   Saba  Female     95  F  Fe
3  Fahad    Male     64  M  Ma
4  Aryan    Male     87  M  Ma

In [19]:
df['Grade'] = df['Score'].apply(lambda x: 'Pass' if x > 85 else 'Fail')

In [20]:
df

    Name  Gender  Score  G  Ge Grade
0    Ali    Male     98  M  Ma  Pass
1   Sana  Female     78  F  Fe  Fail
2   Saba  Female     95  F  Fe  Pass
3  Fahad    Male     64  M  Ma  Fail
4  Aryan    Male     87  M  Ma  Pass